### ISSUE TITLE
Biological application of Moscot: 1.6M cells scRNA data (TOME)

### ISSUE THREAD

**Issue by ManuelGander** [theislab/moscot#181]
We will be comparing Moscot to TOME (Trajectories Of Mouse Embryogenesis,  puplication: https://www.nature.com/articles/s41588-022-01018-x). 
TOME is a rather simple approach. In the 30-dim PCA-space they performed: (their words) "For each pair of adjacent stages (=time points), we performed anchor-based batch correction followed by projecting cells into a shared embedding space. After co-embedding, we applied a k-nearest neighbor (k-NN) based heuristic to connect cell states between adjacent stages. Briefly, for each cell state at the later timepoint, we identified the 5 closest cells from the antecedent timepoint in the co-embedding.
Bootstrapping to obtain a robust estimate (500 iterations with 80% subsampling), we then calculated the
median proportion of such neighbors derived from each potential antecedent cell state, and treated this
as the weight of the corresponding edge." 

You end up with a tree connecting the different cell types (they have a really nice interactive website: http://tome.gs.washington.edu/): 
![tome_tree_with_amount_of_cells](https://user-images.githubusercontent.com/85500983/164936562-812c7f6c-1510-4016-921e-c08e3ddf80b0.png)
(the tree only displays edges with a weight>0.2 in the graph)

The idea is now that Moscot should outperform this k-NN heuristic.  We want to obtain a similar tree as TOME, but with hopefully "better" edge weights. We can then compare the TOME-tree with the Moscot-tree. Qiu et al  (=authors of TOME) already point out several shortcomings of TOME and we can directly test if Moscot performs better in these instances. Additionally, Marius and I have already been thinking about an objective validation metric and we came up with calculating the amount of edge-weights crossing germ layers (Mammals consist of 3 germ layers, Ecto-, Meso-, and Endoderm, and transitions between these germ layers are extremely uncommon). The less edge-weight that crosses germ layers, the better the algorithm.

**Comment by MUCDK** [comment]
closing this as paper-related things should not be discussed here.
