### ISSUE TITLE
`doc` suggestions

### ISSUE THREAD

**Issue by zoepiran** [theislab/moscot#275]
**TBC** 
- update documentation of `scale_cost`. would use OTT's 
```
scale_cost: option to rescale the cost matrix. Implemented scalings are
      'median', 'mean', 'max_cost', 'max_norm' and 'max_bound'.
      Alternatively, a float factor can be given to rescale the cost such
      that ``cost_matrix /= scale_cost``. If `True`, use 'mean'.
```
- add reference methods name in biological problems (i.e. Temporal - WOT, Alignment - PASTE)
- update `moscot.problems.base.**.solve(), moscot.problems.generic.**.solve()` docs, (`**kwargs` dep etc.)

**Comment by MUCDK** [comment]
incorporated in #456
