### ISSUE TITLE
Plot errors instead of costs in `PlotConvergenceMixin`

### ISSUE THREAD

**Issue by michalk8** [theislab/moscot#360]

**Comment by MUCDK** [comment]
@michalk8 what's the status of this? Tbh I think seeing the cost is also nice, maybe add a second plot for errors, or let the user choose?

**Comment by michalk8** [comment]
I think we should split this for and have 2 methods, 1 for costs (is always a 1D array) and the other for errors (sometimes it's not saved in the output + can be 2D, such as in case of GW).
