### ISSUE TITLE
saving a problem object

### ISSUE THREAD

**Issue by zoepiran** [theislab/moscot#399]
attempting to pickle a moscot problem raises `cannot pickle 'mappingproxy' object`
** temporary workaround is saving the `.solution`

**Comment by MUCDK** [comment]
Thanks @zoepiran ,

We now also save the solver from the backend as an attribute, which causes the problem. You can either save the solution as you said or delete the solver. Note the solver is a property, so you would have to do

```
del problem[x,y]._solver._solver
```

Working on it, but will have to talk to Marco/Mike.

**Comment by MUCDK** [comment]
closed by #406
