### ISSUE TITLE
Tutorial notebooks, link broken

### ISSUE THREAD

**Issue by gjhuizing** [theislab/moscot#412]
Hi!

I'm excited to try out your package! For now, I'm copy-pasting the tutorials in my editor because the links to download the notebooks seem broken, e.g. https://github.com/theislab/moscot/edit/main/docs/source/tutorials/tutorial_lineage.ipynb
Am I looking in the wrong branch?

Thanks :)

**Comment by MUCDK** [comment]
Hi  @gjhuizing ,

Thanks for letting us know, I'll work on that shortly.

Apologies for slow responses and some of the tutorials not always being completely up to date. This is due to us still working on a few major changes. We will have a more stable version in a few weeks!

**Comment by gjhuizing** [comment]
No problem, thanks for the thorough documentation :)

**Comment by MUCDK** [comment]
Hi @gjhuizing ,

We have a separate repository for the notebooks, please see [here](https://github.com/theislab/moscot_notebooks/tree/main/docs/source/tutorials). 

We will also update them soon, as mentioned, still work in progress!

**Comment by gjhuizing** [comment]
Awesome, thank you for the link!
