### ISSUE TITLE
Cell transitions plotted twice. 

### ISSUE THREAD

**Issue by Marius1311** [theislab/moscot#435]
Might be related to #430 : `mpl.cell_transition` plots the heatmap twice when using the default `return_fig=True`. Setting this to `False` resolves the issue. It seems that the issue has been introduced in https://github.com/theislab/moscot/commit/1307952da4fe437e41f78405bd623a8ef2214966

**Comment by MUCDK** [comment]
Thanks Marius!

So setting `return_fig` to `False` by default would solve this, right?

I think it's a matter of habitude whether you assign the fig when you return it. But I think it's good to assume people generally don't assign it.

**Comment by MUCDK** [comment]
closed by #434
