### ISSUE TITLE
`GenericAnalysisMixin` redefines push from `CompoundProblem`

### ISSUE THREAD

**Issue by giovp** [theislab/moscot#438]
e.g. the `SinkhornProblem` inherits from `GenericAnalysisMIxin` which has it's own push method
https://github.com/theislab/moscot/blob/a3d4bc0e2851f8024675c4a359fb4f546afd482c/src/moscot/problems/generic/_mixins.py#L93

I would consider removing inheritance of generic problems to analysis mixin.

**Comment by MUCDK** [comment]
I don't think that will work as `push/pull` in the `GenericAnalysisMixin` have the option to save to `adata.uns` for downstream plotting.

We could remove push/pull in the `CompoundBaseProblem` though.

**Comment by MUCDK** [comment]
I would leave it as it is for now @giovp . Please reopen if you would like to.
