### ISSUE TITLE
Spatial plotting

### ISSUE THREAD

**Issue by MUCDK** [theislab/moscot#459]
We should discuss whether we want to have moscot functions visualizing the pull/push distributions in the spatial setting.

Currently, we do have squidpy as a dependency. If we do not use plotting, could we remove it?

**Comment by michalk8** [comment]
I'd say depends how non-trivial/convenient these plotting functions would be.
If it's just
```python
problem.push(...)
squidpy.pl.spatials_scatter(problem.adata, color=...)
```
I'd say it's not necessary. If not, I'd consider having extra requires possibly for each use-case: spatial/temporal/... and importing it locally.
