### ISSUE TITLE
proliferation keys in SpatioTemporalProblem

### ISSUE THREAD

**Issue by zoepiran** [theislab/moscot#462]
Either by calling `score_genes_for_marginals()` or passing `apoptosis_key / proliferation_key` explicitly to the SpatioTemporalProblem they are not updated at the problem level. 
i.e. calling:

```
stp = SpatioTemporalProblem(adata=adata_cur)
stp = stp.score_genes_for_marginals(gene_set_proliferation="mouse", gene_set_apoptosis="mouse")
stp = stp.prepare(
    time_key="time",
    spatial_key="spatial",
    )
```
or 
```
stp = SpatioTemporalProblem(adata=adata)
stp = stp.score_genes_for_marginals(gene_set_proliferation="mouse", gene_set_apoptosis="mouse")
stp = stp.prepare(
    time_key="time",
    spatial_key="spatial",
    apoptosis_key="apoptosis",
    proliferation_key="proliferation"
    )
```

`stp.apoptosis_key ` is correctly assigned (`apoptosis`) but `stp.problems[prob_0].apoptosis_key `, ` stp.problems[(prob_0].prior_growth_rates` are both None.

Running the analogous code (below) for TemporalProblem all are set accurately.

```
tp = SpatioTemporalProblem(adata=adata)
tp = tp.score_genes_for_marginals(gene_set_proliferation="mouse", gene_set_apoptosis="mouse")
tp = tp.prepare( time_key="time")
```

**Comment by MUCDK** [comment]
resolved by #464
