### ISSUE TITLE
Rename GW_{x,y} argument

### ISSUE THREAD

**Issue by michalk8** [theislab/moscot#496]
E.g., [here](https://github.com/theislab/moscot/blob/main/src/moscot/problems/generic/_generic.py#L190-L191) My 2 issues are:
- it may be too technical and doesn't match the `joint_attr`
- it's capitalized

**Comment by MUCDK** [comment]
`gw_source_attr` and `gw_target_attr`?
Any other suggestions @michalk8 ?

**Comment by michalk8** [comment]
Source/target is also a bit deceptive, as it implies one is before the other. How about `{x,y}_attr`?
