### ISSUE TITLE
Highlight moslin

### ISSUE THREAD

**Issue by Marius1311** [theislab/moscot#512]
@MUCDK, we should highlight in the following places that the model/example we present corresponds to moslin: 
- In the tutorial: https://moscot.readthedocs.io/en/latest/notebooks/tutorials/100_lineage.html 
  - I will take care of that. 
- In the lineage tree example: https://moscot.readthedocs.io/en/latest/notebooks/examples/problems/600_leaf_distance.html 
  - if you don't mind, could you take care of that? i.e. Explicitly and prominently mention moslin in the beginning, link to the github, https://github.com/theislab/moslin, for further information. And insert a placeholder to link to the manuscript once it's up

**Comment by MUCDK** [comment]
@Marius1311 are you sure you would like to have a link to the reproducibility github repository? just because we don't do that for any other method/example.

**Comment by Marius1311** [comment]
For now, I think that would be nice as it gives users a bit more context - moslin is a bit different from the other methods we have in moscot.
