### ISSUE TITLE
run tutorials in CI

### ISSUE THREAD

**Issue by giovp** [theislab/moscot#552]
taking inspiration from what it is done in scirpy: https://github.com/scverse/scirpy/blob/main/.github/workflows/test-tutorials.yaml

it would be useful to have a way to test the examples in CI in order to keep track on changes in the API that affect current version of documentation.

**Comment by michalk8** [comment]
I suggest looking into https://myst-nb.readthedocs.io/en/v0.9.0/use/execute.html. Might be possible to set an environment variable for this, wrap it as a `tox` command for convenience and just try building our docs.
