### ISSUE TITLE
Spatial_warp not found when running Alignment problem tutorial

### ISSUE THREAD

**Issue by patrickCNMartin** [theislab/moscot#595]
Hi Moscot team,

I have been playing around with Moscot and trying to run some of the tutorials to get a feel for the tool. 

I am running the Spatial Alignment tutorial as is, copy pasting code at each step. When plotting the 'adata' object, I get an error stating that `spatial_warp` is not found in adata.obsm.

I cannot seem to find the aligned coordinates anywhere. 

I am not sure what I am missing here.

I appreciate your help in this matter.

Patrick

**Comment by giovp** [comment]
hi @patrickCNMartin ,

what are the keys that you have in the spatial anndata after alignment? 
Thank you,
Giovanni

**Comment by ArinaDanilina** [comment]
Hi @patrickCNMartin,

yes, the output of `ap.align(reference = "2")` are the warped coordinates. They will be added to the anndata if you 
specify the `key_added` whenever you call the `.align()` function, in this instance  `ap.align(reference="2", key_added="spatial_warp")` 

Arina

**Comment by patrickCNMartin** [comment]
Hi Arina,

That makes sense! Thank you. 

I was foolishly under the impression that a key would be added automatically since there is no key_added in the vignette. 

In that case - I believe this issue can be closed.

**Comment by MUCDK** [comment]
Please update the tutorials to fix this @giovp , @ArinaDanilina .
