### ISSUE TITLE
update check for categorical dtype

### ISSUE THREAD

**Issue by MUCDK** [theislab/moscot#598]
I got the following future warning:
```FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if not (is_categorical_dtype(col) and is_numeric_dtype(col.cat.categories)):```

We should update the code accordingly.

**Comment by ArinaDanilina** [comment]
```FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead```

**Comment by ArinaDanilina** [comment]
now \Lib\site-packages\anndata\_core\anndata.py:522: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
gets triggered
