### ISSUE TITLE
add tests for geodesic Sinkhorn

### ISSUE THREAD

**Issue by MUCDK** [theislab/moscot#638]
In #633 , we currently only have tests for the `TemporalProblem`. As the pipeline for a graph-based cost is quite different from the remaining costs, we need tests for all problems. Moreover, we should test for different configurations of costs, e.g. linear term geodesic, quadratic terms Euclidean.

Finally, we need examples on how to use the geodesic cost. Here, I would suggest one example notebook for multiple time points with the `TemporalProblem`, and one FGW problem (e.g. `TranslationProblem`) with the linear term being geodesic, and the quadratic e.g. `cosine` cost.

**Comment by selmanozleyen** [comment]
solved with https://github.com/theislab/moscot/pull/677
