### ISSUE TITLE
Bug:cell_transition

### ISSUE THREAD

**Issue by dawangran** [theislab/moscot#652]
I run Analyzing HSPCs with the TemporalProblem from the tutorial:
There is an error, how to deal with it?
<img width="723" alt="image" src="https://github.com/theislab/moscot/assets/94769806/20d91431-45b7-405e-994d-cbc836bb735c">

**Comment by ArinaDanilina** [comment]
Hello @dawangran, the argument should be `key` instead of `uns_key`, so
```
axes[0] = mtp.cell_transition(
    tp,
    fontsize=8,
    figsize=(5, 5),
    return_fig=True,
    ax=axes[0],
    key="transitions_2_3",
)
```
would fix this
