### ISSUE TITLE
Question about "Handling marginals"

### ISSUE THREAD

**Issue by L-traveling** [theislab/moscot#673]
In the [https://moscot.readthedocs.io/en/latest/notebooks/examples/problems/500_passing_marginals.html](url), when I input:
`ap["0", "1"].a`
I will get an array. What I want to know is whether the order of the values in this matrix is the same as the index order of the adata machine with `batch==0`. Like this, 
```
batch_0_data = adata[adata.obs["batch"] == '0'].copy()
batch_0_data.obs["batch"]
```
I guess it's the same, but I can't output the cell index corresponding to `ap["0", "1"].a`. That means a lot to me, thank you.

**Comment by MUCDK** [comment]
Hi @L-traveling ,
in short: yes. 

it's also straightforward for you to verify if you just try it out.

**Comment by L-traveling** [comment]
Ok @MUCDK , thanks.
