### ISSUE TITLE
LineageProblem error

### ISSUE THREAD

**Issue by Marius1311** [theislab/moscot#694]
Hi there, I'm getting `ValueError: Unable to solve a quadratic problem with `alpha = 1` and `xy` supplied.` when trying to solve a `LineageProblem` with `alpha=1.0` and `joint_attr=None`.

**Comment by MUCDK** [comment]
`alpha=1.0` corresponds to a pure Gromov problem, right? We decided to introduce this check to avoid misusage. If you still wanna do a pure Gromov task, I think you can set `LineageProblem[src, tgt].xy = None` after preparing your problem.

**Comment by MUCDK** [comment]
@giovp what's your take?
