### ISSUE TITLE
Refactor: Maybe GW should inherit from FGW instead of vice versa

### ISSUE THREAD

**Issue by selmanozleyen** [theislab/moscot#716]
I was wondering if it would make more sense to inherit `GWProblem` from `FGWProblem` since FGW kind of includes GW in itself. This is a problem since when GW inherites prepare it removes the linear arguments: (`xy_callback` etc.). And because of this we need to use `CompoundProblem.prepare` instead of `super().prepare` which is not ideal if you ask me.

 https://github.com/theislab/moscot/blob/d54060a83de43d779ac50e0125021f2904513e4d/src/moscot/problems/generic/_generic.py#L581-L592

**Comment by MUCDK** [comment]
so you would then throw `NotImplementedError` for all functions which are specific to the fused term?

**Comment by MUCDK** [comment]
Hi @selmanozleyen ,

Please give a brief update on this.

**Comment by selmanozleyen** [comment]
I will close this as I noticed this is a bad idea when I was working on the solve args PR
