### ISSUE TITLE
Add Elastic Costs again or asses if they are necessary or not

### ISSUE THREAD

**Issue by selmanozleyen** [theislab/moscot#726]
In this PR https://github.com/theislab/moscot/pull/725 I removed the Elastic cost functions since ottjax removed them with this commit: https://github.com/ott-jax/ott/commit/d5d8a4712dddd9b24d6906bee1ea3835f4e7ac13

We should decide what we are going to do about this

**Comment by marcocuturi** [comment]
@michalk8 I think this should be easy?

**Comment by michalk8** [comment]
Yes, they've been refactored to just use `RegTICost` + a regularization class; should be fairly easy to incorporate the changes.

**Comment by selmanozleyen** [comment]
if then necessary we'll add it, so I am closing this issue for now. Just wanted to know how important it was to replace them
