### ISSUE TITLE
output the raw cell transition data without aggregation

### ISSUE THREAD

**Issue by Xian123123123** [theislab/moscot#733]
Hi, thank you for the amazing work!
How could one output the raw cell transition data without aggregation? For example, in 200_cell_transitions.ipynb, is it possible to output the entire source x target matrix? thanks.

**Comment by MUCDK** [comment]
Hi @Xian123123123 ,

I guess that you just wanna have the transport matrix then?

You can access this via `tp[t_0, t_1].solution.transport_matrix`, see https://moscot.readthedocs.io/en/latest/genapi/moscot.backends.ott.OTTOutput.transport_matrix.html#moscot.backends.ott.OTTOutput.transport_matrix

**Comment by Xian123123123** [comment]
Yes. Could you share an example code? Thanks.

**Comment by Xian123123123** [comment]
Thank you @MUCDK , how can I generate the full transport matrix from 700_tutorial_perturbation_with_Sinkhorn.ipynb (i.e. between a drug and the control)?

**Comment by MUCDK** [comment]
you can use e.g. `sp['Dacinostat (LAQ824)', 'control').solution.transport_matrix`

**Comment by Xian123123123** [comment]
thank you @MUCDK. with the full transport matrix, how does one decide which link is "real", i.e. how does one define a threshold?

**Comment by MUCDK** [comment]
First, this depends on the entropy regularisation. The higher `epsilon` is, the higher the stochasticity . Hence, there is no single answer to this. 

You could take the argmax for each row, or use the sparsification method to set a large number of the entries to 0: https://moscot.readthedocs.io/en/latest/genapi/moscot.base.output.BaseSolverOutput.sparsify.html#moscot.base.output.BaseSolverOutput.sparsify

**Comment by MUCDK** [comment]
I'm closing this for now. Please reopen if necessary.
